### ISSUE TITLE
Not working in release mode. All works fine in debug mode. If I copy the file directly and use it, it works in release as well.

### ISSUE THREAD

**Issue by ghost** [ananddayalan/react-native-material-design-searchbar#1]
Not working in release mode. All works fine in debug mode. If I copy the file directly and use it, it works in the release as well, but doesn't work if I import the module directly. I have to copy files and put it into my solution and it works fine in release and debug.

**Comment by scerelli** [comment]
@jo2010 if he merge my pr and release on npm eveything will work fine

**Comment by ananddayalan** [comment]
Closing the issue. PR#4 fixes the issue.
https://github.com/ananddayalan/react-native-material-design-searchbar/pull/4
