### ISSUE TITLE
dismissKeyboard can't be found

### ISSUE THREAD

**Issue by scerelli** [ananddayalan/react-native-material-design-searchbar#2]
I just installed your component but it doesn't work. It throws an error on dismissKeyboard because it can't find it in the package dependencies

**Comment by scerelli** [comment]
PR Fix https://github.com/ananddayalan/react-native-material-design-searchbar/pull/3

**Comment by ananddayalan** [comment]
Thank for PR. Merged it.

**Comment by scerelli** [comment]
@ananddayalan  can you update the package on npm?

**Comment by arstiefel** [comment]
+1 Update npm please

**Comment by ananddayalan** [comment]
@stief510 @scerelli Sorry for the delay. Just updated the npm
