### ISSUE TITLE
add screenshot to readme

### ISSUE THREAD

**Issue by vonovak** [ananddayalan/react-native-material-design-searchbar#29]
please add a screenshot so people know what it looks like, thanks!

**Comment by jordanmkoncz** [comment]
Was just about to create an issue for this too. The README has links to two screenshot images, but the image URLs lead to a 404 page.

**Comment by Noitidart** [comment]
Images are broken :( I also was wondering if this was the right component for me.

**Comment by Noitidart** [comment]
Thank you very much!
