### ISSUE TITLE
error with loaders?

### ISSUE THREAD

**Issue by omegaht** [ananddayalan/react-native-material-design-searchbar#5]
hi im new to react, and i cant test the component because it fails here:

node_modules/react-native-material-design-searchbar/SearchBar.js Unexpected token (30:19)
You may need an appropriate loader to handle this file type.

any ideas?

**Comment by ananddayalan** [comment]
I think it could be bcoz of some Babel issues or missing Babel modules. What version and modules of Babel do you use?

**Comment by ananddayalan** [comment]
No response from OP
