### ISSUE TITLE
Remove line under search input

### ISSUE THREAD

**Issue by iRoachie** [ananddayalan/react-native-material-design-searchbar#8]
Is there anyway to remove the line under the search?
![screen shot 2016-12-24 at 6 12 43 pm](https://cloud.githubusercontent.com/assets/5962998/21468919/947e7674-ca04-11e6-82b0-d715dcffc476.jpg)

**Comment by AlisonWonderlandApps** [comment]
this is android default search component. You'd need to remove it in android i assume / rebuild a component

**Comment by ananddayalan** [comment]
#8
